export const SPECIES = [
  'African Pompano','Alabama Bass','Albacore','Almaco Jack','Apache Trout',
  'Arctic Char','Atlantic Croaker','Atlantic Sailfish','Atlantic Salmon',
  'Barred Surfperch','Bigeye Tuna','Black Crappie','Black Drum','Black Grouper',
  'Black Sea Bass','Blackfin Tuna','Blacktip Shark','Blue Catfish','Blue Marlin',
  'Bluefin Tuna','Bluegill','Bocaccio','Bonito','Bonnethead','Brook Trout',
  'Brown Trout','Bull Shark','Burbot','California Halibut','Canary Rockfish',
  'Cero Mackerel','Channel Catfish','Chinook Salmon','Chum Salmon','Cisco',
  'Cobia','Coho Salmon','Common Carp','Copper Rockfish','Crevalle Jack',
  'Cubera Snapper','Cutthroat Trout','Dolly Varden','Dover Sole',
  'Flathead Catfish','Florida Pompano','Freshwater Drum','Gag Grouper',
  'Giant Manta Ray','Gila Trout','Golden Trout','Goliath Grouper',
  'Grass Carp','Great Barracuda','Greater Amberjack','Green Sunfish',
  'Guadalupe Bass','Gulf Flounder','Hogfish','Inconnu (Sheefish)',
  'King Mackerel','Lahontan Cutthroat','Lake Trout','Lake Whitefish',
  'Lane Snapper','Largemouth Bass','Lemon Shark','Lionfish','Little Tunny',
  'Longear Sunfish','Longnose Gar','Lookdown','Mahi Mahi','Mangrove Snapper',
  'Muskellunge','Mutton Snapper','Nassau Grouper','Northern Pike',
  'Northern Snakehead','Nurse Shark','Oscar','Pacific Halibut',
  'Paddlefish','Peacock Bass (Butterfly)','Permit','Pigfish','Pink Salmon',
  'Pumpkinseed','Rainbow Trout','Razorback Sucker','Red Drum','Red Grouper',
  'Red Snapper','Redear Sunfish','Redeye Bass','Roanoke Bass','Rock Bass',
  'Scamp','Sheepshead','Shoal Bass','Shortfin Mako','Silver Carp',
  'Skipjack Tuna','Smallmouth Bass','Smallmouth Buffalo','Snook',
  'Sockeye Salmon','Southern Flounder','Spadefish','Spanish Mackerel',
  'Speckled Peacock Bass','Spotted Bass','Spotted Seatrout','Steelhead',
  'Striped Bass','Summer Flounder','Suwannee Bass','Swordfish','Tautog',
  'Thresher Shark','Tiger Shark','Tiger Trout','Vermilion Snapper',
  'Wahoo','Walleye','Warmouth','Warsaw Grouper','Weakfish','White Bass',
  'White Catfish','White Crappie','White Marlin','White Seabass',
  'White Sturgeon','Windowpane Flounder','Winter Flounder','Yellow Bullhead',
  'Yellow Perch','Yellowfin Tuna','Yellowtail Snapper',
]
